apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-mysfits-eks
  namespace: default
  labels:
    app: mythical-mysfits-eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mythical-mysfits-eks
  template:
    metadata:
      labels:
        app: mythical-mysfits-eks
    spec:
      serviceAccountName: mythical-misfit
      containers:
        - name: mythical-mysfits-eks
          image: 716713632458.dkr.ecr.us-east-1.amazonaws.com/monolith-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DDB_TABLE_NAME
              value: MysfitsTable
            - name: AWS_DEFAULT_REGION
              value: us-east-1

---
apiVersion: v1
kind: Service
metadata:
  name: mythical-mysfits-eks
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mythical-mysfits-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
